// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package org.cheetah.predator.protocol;

public final class MessageBuf {
  private MessageBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .netty.Message.Header header = 1;
    /**
     * <code>required .netty.Message.Header header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>required .netty.Message.Header header = 1;</code>
     */
    Message.Header getHeader();
    /**
     * <code>required .netty.Message.Header header = 1;</code>
     */
    Message.HeaderOrBuilder getHeaderOrBuilder();

    // repeated .netty.Message.Body body = 2;
    /**
     * <code>repeated .netty.Message.Body body = 2;</code>
     */
    java.util.List<Message.Body>
        getBodyList();
    /**
     * <code>repeated .netty.Message.Body body = 2;</code>
     */
    Message.Body getBody(int index);
    /**
     * <code>repeated .netty.Message.Body body = 2;</code>
     */
    int getBodyCount();
    /**
     * <code>repeated .netty.Message.Body body = 2;</code>
     */
    java.util.List<? extends Message.BodyOrBuilder>
        getBodyOrBuilderList();
    /**
     * <code>repeated .netty.Message.Body body = 2;</code>
     */
    Message.BodyOrBuilder getBodyOrBuilder(
            int index);

    // optional bytes attachment = 8;
    /**
     * <code>optional bytes attachment = 8;</code>
     */
    boolean hasAttachment();
    /**
     * <code>optional bytes attachment = 8;</code>
     */
    com.google.protobuf.ByteString getAttachment();
  }
  /**
   * Protobuf type {@code netty.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage
      implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }

    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              Header.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(Header.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                body_ = new java.util.ArrayList<Body>();
                mutable_bitField0_ |= 0x00000002;
              }
              body_.add(input.readMessage(Body.PARSER, extensionRegistry));
              break;
            }
            case 66: {
              bitField0_ |= 0x00000002;
              attachment_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          body_ = java.util.Collections.unmodifiableList(body_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageBuf.internal_static_netty_Message_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageBuf.internal_static_netty_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Message> PARSER =
        new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public interface HeaderOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required fixed32 type = 1;
      /**
       * <code>required fixed32 type = 1;</code>
       */
      boolean hasType();
      /**
       * <code>required fixed32 type = 1;</code>
       */
      int getType();

      // required string from = 2;
      /**
       * <code>required string from = 2;</code>
       */
      boolean hasFrom();
      /**
       * <code>required string from = 2;</code>
       */
      String getFrom();
      /**
       * <code>required string from = 2;</code>
       */
      com.google.protobuf.ByteString
          getFromBytes();

      // required string to = 3;
      /**
       * <code>required string to = 3;</code>
       */
      boolean hasTo();
      /**
       * <code>required string to = 3;</code>
       */
      String getTo();
      /**
       * <code>required string to = 3;</code>
       */
      com.google.protobuf.ByteString
          getToBytes();

      // required string delivery_id = 4;
      /**
       * <code>required string delivery_id = 4;</code>
       */
      boolean hasDeliveryId();
      /**
       * <code>required string delivery_id = 4;</code>
       */
      String getDeliveryId();
      /**
       * <code>required string delivery_id = 4;</code>
       */
      com.google.protobuf.ByteString
          getDeliveryIdBytes();

      // required fixed64 delivery_time = 5;
      /**
       * <code>required fixed64 delivery_time = 5;</code>
       */
      boolean hasDeliveryTime();
      /**
       * <code>required fixed64 delivery_time = 5;</code>
       */
      long getDeliveryTime();

      // required string device_id = 6;
      /**
       * <code>required string device_id = 6;</code>
       */
      boolean hasDeviceId();
      /**
       * <code>required string device_id = 6;</code>
       */
      String getDeviceId();
      /**
       * <code>required string device_id = 6;</code>
       */
      com.google.protobuf.ByteString
          getDeviceIdBytes();

      // required string device_platform = 7;
      /**
       * <code>required string device_platform = 7;</code>
       */
      boolean hasDevicePlatform();
      /**
       * <code>required string device_platform = 7;</code>
       */
      String getDevicePlatform();
      /**
       * <code>required string device_platform = 7;</code>
       */
      com.google.protobuf.ByteString
          getDevicePlatformBytes();
    }
    /**
     * Protobuf type {@code netty.Message.Header}
     */
    public static final class Header extends
        com.google.protobuf.GeneratedMessage
        implements HeaderOrBuilder {
      // Use Header.newBuilder() to construct.
      private Header(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Header(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Header defaultInstance;
      public static Header getDefaultInstance() {
        return defaultInstance;
      }

      public Header getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Header(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 13: {
                bitField0_ |= 0x00000001;
                type_ = input.readFixed32();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                from_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                to_ = input.readBytes();
                break;
              }
              case 34: {
                bitField0_ |= 0x00000008;
                deliveryId_ = input.readBytes();
                break;
              }
              case 41: {
                bitField0_ |= 0x00000010;
                deliveryTime_ = input.readFixed64();
                break;
              }
              case 50: {
                bitField0_ |= 0x00000020;
                deviceId_ = input.readBytes();
                break;
              }
              case 58: {
                bitField0_ |= 0x00000040;
                devicePlatform_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageBuf.internal_static_netty_Message_Header_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageBuf.internal_static_netty_Message_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Header.class, Builder.class);
      }

      public static com.google.protobuf.Parser<Header> PARSER =
          new com.google.protobuf.AbstractParser<Header>() {
        public Header parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Header(input, extensionRegistry);
        }
      };

      @Override
      public com.google.protobuf.Parser<Header> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required fixed32 type = 1;
      public static final int TYPE_FIELD_NUMBER = 1;
      private int type_;
      /**
       * <code>required fixed32 type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required fixed32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }

      // required string from = 2;
      public static final int FROM_FIELD_NUMBER = 2;
      private Object from_;
      /**
       * <code>required string from = 2;</code>
       */
      public boolean hasFrom() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string from = 2;</code>
       */
      public String getFrom() {
        Object ref = from_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            from_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string from = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFromBytes() {
        Object ref = from_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          from_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string to = 3;
      public static final int TO_FIELD_NUMBER = 3;
      private Object to_;
      /**
       * <code>required string to = 3;</code>
       */
      public boolean hasTo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string to = 3;</code>
       */
      public String getTo() {
        Object ref = to_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            to_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string to = 3;</code>
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string delivery_id = 4;
      public static final int DELIVERY_ID_FIELD_NUMBER = 4;
      private Object deliveryId_;
      /**
       * <code>required string delivery_id = 4;</code>
       */
      public boolean hasDeliveryId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string delivery_id = 4;</code>
       */
      public String getDeliveryId() {
        Object ref = deliveryId_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deliveryId_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string delivery_id = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDeliveryIdBytes() {
        Object ref = deliveryId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deliveryId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required fixed64 delivery_time = 5;
      public static final int DELIVERY_TIME_FIELD_NUMBER = 5;
      private long deliveryTime_;
      /**
       * <code>required fixed64 delivery_time = 5;</code>
       */
      public boolean hasDeliveryTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required fixed64 delivery_time = 5;</code>
       */
      public long getDeliveryTime() {
        return deliveryTime_;
      }

      // required string device_id = 6;
      public static final int DEVICE_ID_FIELD_NUMBER = 6;
      private Object deviceId_;
      /**
       * <code>required string device_id = 6;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string device_id = 6;</code>
       */
      public String getDeviceId() {
        Object ref = deviceId_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceId_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string device_id = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string device_platform = 7;
      public static final int DEVICE_PLATFORM_FIELD_NUMBER = 7;
      private Object devicePlatform_;
      /**
       * <code>required string device_platform = 7;</code>
       */
      public boolean hasDevicePlatform() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string device_platform = 7;</code>
       */
      public String getDevicePlatform() {
        Object ref = devicePlatform_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            devicePlatform_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string device_platform = 7;</code>
       */
      public com.google.protobuf.ByteString
          getDevicePlatformBytes() {
        Object ref = devicePlatform_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          devicePlatform_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        type_ = 0;
        from_ = "";
        to_ = "";
        deliveryId_ = "";
        deliveryTime_ = 0L;
        deviceId_ = "";
        devicePlatform_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasFrom()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasTo()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasDeliveryId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasDeliveryTime()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasDeviceId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasDevicePlatform()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeFixed32(1, type_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getFromBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getToBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, getDeliveryIdBytes());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeFixed64(5, deliveryTime_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeBytes(6, getDeviceIdBytes());
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          output.writeBytes(7, getDevicePlatformBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFixed32Size(1, type_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getFromBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getToBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, getDeliveryIdBytes());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFixed64Size(5, deliveryTime_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(6, getDeviceIdBytes());
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(7, getDevicePlatformBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static Header parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Header parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Header parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Header parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Header parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Header parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static Header parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static Header parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static Header parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Header parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(Header prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code netty.Message.Header}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements HeaderOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return MessageBuf.internal_static_netty_Message_Header_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return MessageBuf.internal_static_netty_Message_Header_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Header.class, Builder.class);
        }

        // Construct using MessageBuf.Message.Header.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          type_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          from_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          to_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          deliveryId_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          deliveryTime_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000010);
          deviceId_ = "";
          bitField0_ = (bitField0_ & ~0x00000020);
          devicePlatform_ = "";
          bitField0_ = (bitField0_ & ~0x00000040);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return MessageBuf.internal_static_netty_Message_Header_descriptor;
        }

        public Header getDefaultInstanceForType() {
          return Header.getDefaultInstance();
        }

        public Header build() {
          Header result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Header buildPartial() {
          Header result = new Header(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.from_ = from_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.to_ = to_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.deliveryId_ = deliveryId_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.deliveryTime_ = deliveryTime_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.deviceId_ = deviceId_;
          if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
            to_bitField0_ |= 0x00000040;
          }
          result.devicePlatform_ = devicePlatform_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Header) {
            return mergeFrom((Header)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Header other) {
          if (other == Header.getDefaultInstance()) return this;
          if (other.hasType()) {
            setType(other.getType());
          }
          if (other.hasFrom()) {
            bitField0_ |= 0x00000002;
            from_ = other.from_;
            onChanged();
          }
          if (other.hasTo()) {
            bitField0_ |= 0x00000004;
            to_ = other.to_;
            onChanged();
          }
          if (other.hasDeliveryId()) {
            bitField0_ |= 0x00000008;
            deliveryId_ = other.deliveryId_;
            onChanged();
          }
          if (other.hasDeliveryTime()) {
            setDeliveryTime(other.getDeliveryTime());
          }
          if (other.hasDeviceId()) {
            bitField0_ |= 0x00000020;
            deviceId_ = other.deviceId_;
            onChanged();
          }
          if (other.hasDevicePlatform()) {
            bitField0_ |= 0x00000040;
            devicePlatform_ = other.devicePlatform_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasType()) {
            
            return false;
          }
          if (!hasFrom()) {
            
            return false;
          }
          if (!hasTo()) {
            
            return false;
          }
          if (!hasDeliveryId()) {
            
            return false;
          }
          if (!hasDeliveryTime()) {
            
            return false;
          }
          if (!hasDeviceId()) {
            
            return false;
          }
          if (!hasDevicePlatform()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Header parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Header) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required fixed32 type = 1;
        private int type_ ;
        /**
         * <code>required fixed32 type = 1;</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required fixed32 type = 1;</code>
         */
        public int getType() {
          return type_;
        }
        /**
         * <code>required fixed32 type = 1;</code>
         */
        public Builder setType(int value) {
          bitField0_ |= 0x00000001;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required fixed32 type = 1;</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = 0;
          onChanged();
          return this;
        }

        // required string from = 2;
        private Object from_ = "";
        /**
         * <code>required string from = 2;</code>
         */
        public boolean hasFrom() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string from = 2;</code>
         */
        public String getFrom() {
          Object ref = from_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            from_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string from = 2;</code>
         */
        public com.google.protobuf.ByteString
            getFromBytes() {
          Object ref = from_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            from_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string from = 2;</code>
         */
        public Builder setFrom(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          from_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string from = 2;</code>
         */
        public Builder clearFrom() {
          bitField0_ = (bitField0_ & ~0x00000002);
          from_ = getDefaultInstance().getFrom();
          onChanged();
          return this;
        }
        /**
         * <code>required string from = 2;</code>
         */
        public Builder setFromBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          from_ = value;
          onChanged();
          return this;
        }

        // required string to = 3;
        private Object to_ = "";
        /**
         * <code>required string to = 3;</code>
         */
        public boolean hasTo() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required string to = 3;</code>
         */
        public String getTo() {
          Object ref = to_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            to_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string to = 3;</code>
         */
        public com.google.protobuf.ByteString
            getToBytes() {
          Object ref = to_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            to_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string to = 3;</code>
         */
        public Builder setTo(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          to_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string to = 3;</code>
         */
        public Builder clearTo() {
          bitField0_ = (bitField0_ & ~0x00000004);
          to_ = getDefaultInstance().getTo();
          onChanged();
          return this;
        }
        /**
         * <code>required string to = 3;</code>
         */
        public Builder setToBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          to_ = value;
          onChanged();
          return this;
        }

        // required string delivery_id = 4;
        private Object deliveryId_ = "";
        /**
         * <code>required string delivery_id = 4;</code>
         */
        public boolean hasDeliveryId() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required string delivery_id = 4;</code>
         */
        public String getDeliveryId() {
          Object ref = deliveryId_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            deliveryId_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string delivery_id = 4;</code>
         */
        public com.google.protobuf.ByteString
            getDeliveryIdBytes() {
          Object ref = deliveryId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            deliveryId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string delivery_id = 4;</code>
         */
        public Builder setDeliveryId(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          deliveryId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string delivery_id = 4;</code>
         */
        public Builder clearDeliveryId() {
          bitField0_ = (bitField0_ & ~0x00000008);
          deliveryId_ = getDefaultInstance().getDeliveryId();
          onChanged();
          return this;
        }
        /**
         * <code>required string delivery_id = 4;</code>
         */
        public Builder setDeliveryIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          deliveryId_ = value;
          onChanged();
          return this;
        }

        // required fixed64 delivery_time = 5;
        private long deliveryTime_ ;
        /**
         * <code>required fixed64 delivery_time = 5;</code>
         */
        public boolean hasDeliveryTime() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>required fixed64 delivery_time = 5;</code>
         */
        public long getDeliveryTime() {
          return deliveryTime_;
        }
        /**
         * <code>required fixed64 delivery_time = 5;</code>
         */
        public Builder setDeliveryTime(long value) {
          bitField0_ |= 0x00000010;
          deliveryTime_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required fixed64 delivery_time = 5;</code>
         */
        public Builder clearDeliveryTime() {
          bitField0_ = (bitField0_ & ~0x00000010);
          deliveryTime_ = 0L;
          onChanged();
          return this;
        }

        // required string device_id = 6;
        private Object deviceId_ = "";
        /**
         * <code>required string device_id = 6;</code>
         */
        public boolean hasDeviceId() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>required string device_id = 6;</code>
         */
        public String getDeviceId() {
          Object ref = deviceId_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            deviceId_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string device_id = 6;</code>
         */
        public com.google.protobuf.ByteString
            getDeviceIdBytes() {
          Object ref = deviceId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            deviceId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string device_id = 6;</code>
         */
        public Builder setDeviceId(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
          deviceId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string device_id = 6;</code>
         */
        public Builder clearDeviceId() {
          bitField0_ = (bitField0_ & ~0x00000020);
          deviceId_ = getDefaultInstance().getDeviceId();
          onChanged();
          return this;
        }
        /**
         * <code>required string device_id = 6;</code>
         */
        public Builder setDeviceIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
          deviceId_ = value;
          onChanged();
          return this;
        }

        // required string device_platform = 7;
        private Object devicePlatform_ = "";
        /**
         * <code>required string device_platform = 7;</code>
         */
        public boolean hasDevicePlatform() {
          return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>required string device_platform = 7;</code>
         */
        public String getDevicePlatform() {
          Object ref = devicePlatform_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            devicePlatform_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string device_platform = 7;</code>
         */
        public com.google.protobuf.ByteString
            getDevicePlatformBytes() {
          Object ref = devicePlatform_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            devicePlatform_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string device_platform = 7;</code>
         */
        public Builder setDevicePlatform(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
          devicePlatform_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string device_platform = 7;</code>
         */
        public Builder clearDevicePlatform() {
          bitField0_ = (bitField0_ & ~0x00000040);
          devicePlatform_ = getDefaultInstance().getDevicePlatform();
          onChanged();
          return this;
        }
        /**
         * <code>required string device_platform = 7;</code>
         */
        public Builder setDevicePlatformBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
          devicePlatform_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:netty.Message.Header)
      }

      static {
        defaultInstance = new Header(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:netty.Message.Header)
    }

    public interface BodyOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string key = 1;
      /**
       * <code>required string key = 1;</code>
       */
      boolean hasKey();
      /**
       * <code>required string key = 1;</code>
       */
      String getKey();
      /**
       * <code>required string key = 1;</code>
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      // required string value = 2;
      /**
       * <code>required string value = 2;</code>
       */
      boolean hasValue();
      /**
       * <code>required string value = 2;</code>
       */
      String getValue();
      /**
       * <code>required string value = 2;</code>
       */
      com.google.protobuf.ByteString
          getValueBytes();
    }
    /**
     * Protobuf type {@code netty.Message.Body}
     */
    public static final class Body extends
        com.google.protobuf.GeneratedMessage
        implements BodyOrBuilder {
      // Use Body.newBuilder() to construct.
      private Body(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Body(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Body defaultInstance;
      public static Body getDefaultInstance() {
        return defaultInstance;
      }

      public Body getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Body(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                key_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                value_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageBuf.internal_static_netty_Message_Body_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageBuf.internal_static_netty_Message_Body_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Body.class, Builder.class);
      }

      public static com.google.protobuf.Parser<Body> PARSER =
          new com.google.protobuf.AbstractParser<Body>() {
        public Body parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Body(input, extensionRegistry);
        }
      };

      @Override
      public com.google.protobuf.Parser<Body> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string key = 1;
      public static final int KEY_FIELD_NUMBER = 1;
      private Object key_;
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public String getKey() {
        Object ref = key_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string value = 2;
      public static final int VALUE_FIELD_NUMBER = 2;
      private Object value_;
      /**
       * <code>required string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string value = 2;</code>
       */
      public String getValue() {
        Object ref = value_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        key_ = "";
        value_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasKey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getValueBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getValueBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static Body parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Body parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Body parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Body parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Body parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Body parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static Body parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static Body parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static Body parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Body parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(Body prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code netty.Message.Body}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements BodyOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return MessageBuf.internal_static_netty_Message_Body_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return MessageBuf.internal_static_netty_Message_Body_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Body.class, Builder.class);
        }

        // Construct using MessageBuf.Message.Body.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          key_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return MessageBuf.internal_static_netty_Message_Body_descriptor;
        }

        public Body getDefaultInstanceForType() {
          return Body.getDefaultInstance();
        }

        public Body build() {
          Body result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Body buildPartial() {
          Body result = new Body(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Body) {
            return mergeFrom((Body)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Body other) {
          if (other == Body.getDefaultInstance()) return this;
          if (other.hasKey()) {
            bitField0_ |= 0x00000001;
            key_ = other.key_;
            onChanged();
          }
          if (other.hasValue()) {
            bitField0_ |= 0x00000002;
            value_ = other.value_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasKey()) {
            
            return false;
          }
          if (!hasValue()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Body parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Body) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string key = 1;
        private Object key_ = "";
        /**
         * <code>required string key = 1;</code>
         */
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string key = 1;</code>
         */
        public String getKey() {
          Object ref = key_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            key_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string key = 1;</code>
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder setKey(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        /**
         * <code>required string key = 1;</code>
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }

        // required string value = 2;
        private Object value_ = "";
        /**
         * <code>required string value = 2;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string value = 2;</code>
         */
        public String getValue() {
          Object ref = value_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            value_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string value = 2;</code>
         */
        public com.google.protobuf.ByteString
            getValueBytes() {
          Object ref = value_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            value_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string value = 2;</code>
         */
        public Builder setValue(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string value = 2;</code>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        /**
         * <code>required string value = 2;</code>
         */
        public Builder setValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:netty.Message.Body)
      }

      static {
        defaultInstance = new Body(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:netty.Message.Body)
    }

    private int bitField0_;
    // required .netty.Message.Header header = 1;
    public static final int HEADER_FIELD_NUMBER = 1;
    private Header header_;
    /**
     * <code>required .netty.Message.Header header = 1;</code>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .netty.Message.Header header = 1;</code>
     */
    public Header getHeader() {
      return header_;
    }
    /**
     * <code>required .netty.Message.Header header = 1;</code>
     */
    public HeaderOrBuilder getHeaderOrBuilder() {
      return header_;
    }

    // repeated .netty.Message.Body body = 2;
    public static final int BODY_FIELD_NUMBER = 2;
    private java.util.List<Body> body_;
    /**
     * <code>repeated .netty.Message.Body body = 2;</code>
     */
    public java.util.List<Body> getBodyList() {
      return body_;
    }
    /**
     * <code>repeated .netty.Message.Body body = 2;</code>
     */
    public java.util.List<? extends BodyOrBuilder>
        getBodyOrBuilderList() {
      return body_;
    }
    /**
     * <code>repeated .netty.Message.Body body = 2;</code>
     */
    public int getBodyCount() {
      return body_.size();
    }
    /**
     * <code>repeated .netty.Message.Body body = 2;</code>
     */
    public Body getBody(int index) {
      return body_.get(index);
    }
    /**
     * <code>repeated .netty.Message.Body body = 2;</code>
     */
    public BodyOrBuilder getBodyOrBuilder(
        int index) {
      return body_.get(index);
    }

    // optional bytes attachment = 8;
    public static final int ATTACHMENT_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString attachment_;
    /**
     * <code>optional bytes attachment = 8;</code>
     */
    public boolean hasAttachment() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes attachment = 8;</code>
     */
    public com.google.protobuf.ByteString getAttachment() {
      return attachment_;
    }

    private void initFields() {
      header_ = Header.getDefaultInstance();
      body_ = java.util.Collections.emptyList();
      attachment_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getBodyCount(); i++) {
        if (!getBody(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, header_);
      }
      for (int i = 0; i < body_.size(); i++) {
        output.writeMessage(2, body_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(8, attachment_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, header_);
      }
      for (int i = 0; i < body_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, body_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, attachment_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netty.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageBuf.internal_static_netty_Message_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageBuf.internal_static_netty_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Message.class, Builder.class);
      }

      // Construct using MessageBuf.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
          getBodyFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = Header.getDefaultInstance();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (bodyBuilder_ == null) {
          body_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          bodyBuilder_.clear();
        }
        attachment_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageBuf.internal_static_netty_Message_descriptor;
      }

      public Message getDefaultInstanceForType() {
        return Message.getDefaultInstance();
      }

      public Message build() {
        Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Message buildPartial() {
        Message result = new Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (bodyBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            body_ = java.util.Collections.unmodifiableList(body_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.body_ = body_;
        } else {
          result.body_ = bodyBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.attachment_ = attachment_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message) {
          return mergeFrom((Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Message other) {
        if (other == Message.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (bodyBuilder_ == null) {
          if (!other.body_.isEmpty()) {
            if (body_.isEmpty()) {
              body_ = other.body_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureBodyIsMutable();
              body_.addAll(other.body_);
            }
            onChanged();
          }
        } else {
          if (!other.body_.isEmpty()) {
            if (bodyBuilder_.isEmpty()) {
              bodyBuilder_.dispose();
              bodyBuilder_ = null;
              body_ = other.body_;
              bitField0_ = (bitField0_ & ~0x00000002);
              bodyBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBodyFieldBuilder() : null;
            } else {
              bodyBuilder_.addAllMessages(other.body_);
            }
          }
        }
        if (other.hasAttachment()) {
          setAttachment(other.getAttachment());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHeader()) {
          
          return false;
        }
        if (!getHeader().isInitialized()) {
          
          return false;
        }
        for (int i = 0; i < getBodyCount(); i++) {
          if (!getBody(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .netty.Message.Header header = 1;
      private Header header_ = Header.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Header, Header.Builder, HeaderOrBuilder> headerBuilder_;
      /**
       * <code>required .netty.Message.Header header = 1;</code>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .netty.Message.Header header = 1;</code>
       */
      public Header getHeader() {
        if (headerBuilder_ == null) {
          return header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .netty.Message.Header header = 1;</code>
       */
      public Builder setHeader(Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .netty.Message.Header header = 1;</code>
       */
      public Builder setHeader(
          Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .netty.Message.Header header = 1;</code>
       */
      public Builder mergeHeader(Header value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              header_ != Header.getDefaultInstance()) {
            header_ =
              Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .netty.Message.Header header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = Header.getDefaultInstance();
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .netty.Message.Header header = 1;</code>
       */
      public Header.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .netty.Message.Header header = 1;</code>
       */
      public HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_;
        }
      }
      /**
       * <code>required .netty.Message.Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Header, Header.Builder, HeaderOrBuilder>
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Header, Header.Builder, HeaderOrBuilder>(
                  header_,
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      // repeated .netty.Message.Body body = 2;
      private java.util.List<Body> body_ =
        java.util.Collections.emptyList();
      private void ensureBodyIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          body_ = new java.util.ArrayList<Body>(body_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Body, Body.Builder, BodyOrBuilder> bodyBuilder_;

      /**
       * <code>repeated .netty.Message.Body body = 2;</code>
       */
      public java.util.List<Body> getBodyList() {
        if (bodyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(body_);
        } else {
          return bodyBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .netty.Message.Body body = 2;</code>
       */
      public int getBodyCount() {
        if (bodyBuilder_ == null) {
          return body_.size();
        } else {
          return bodyBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .netty.Message.Body body = 2;</code>
       */
      public Body getBody(int index) {
        if (bodyBuilder_ == null) {
          return body_.get(index);
        } else {
          return bodyBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .netty.Message.Body body = 2;</code>
       */
      public Builder setBody(
          int index, Body value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBodyIsMutable();
          body_.set(index, value);
          onChanged();
        } else {
          bodyBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .netty.Message.Body body = 2;</code>
       */
      public Builder setBody(
          int index, Body.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          body_.set(index, builderForValue.build());
          onChanged();
        } else {
          bodyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .netty.Message.Body body = 2;</code>
       */
      public Builder addBody(Body value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBodyIsMutable();
          body_.add(value);
          onChanged();
        } else {
          bodyBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .netty.Message.Body body = 2;</code>
       */
      public Builder addBody(
          int index, Body value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBodyIsMutable();
          body_.add(index, value);
          onChanged();
        } else {
          bodyBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .netty.Message.Body body = 2;</code>
       */
      public Builder addBody(
          Body.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          body_.add(builderForValue.build());
          onChanged();
        } else {
          bodyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .netty.Message.Body body = 2;</code>
       */
      public Builder addBody(
          int index, Body.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          body_.add(index, builderForValue.build());
          onChanged();
        } else {
          bodyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .netty.Message.Body body = 2;</code>
       */
      public Builder addAllBody(
          Iterable<? extends Body> values) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          super.addAll(values, body_);
          onChanged();
        } else {
          bodyBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .netty.Message.Body body = 2;</code>
       */
      public Builder clearBody() {
        if (bodyBuilder_ == null) {
          body_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          bodyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .netty.Message.Body body = 2;</code>
       */
      public Builder removeBody(int index) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          body_.remove(index);
          onChanged();
        } else {
          bodyBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .netty.Message.Body body = 2;</code>
       */
      public Body.Builder getBodyBuilder(
          int index) {
        return getBodyFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .netty.Message.Body body = 2;</code>
       */
      public BodyOrBuilder getBodyOrBuilder(
          int index) {
        if (bodyBuilder_ == null) {
          return body_.get(index);  } else {
          return bodyBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .netty.Message.Body body = 2;</code>
       */
      public java.util.List<? extends BodyOrBuilder>
           getBodyOrBuilderList() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(body_);
        }
      }
      /**
       * <code>repeated .netty.Message.Body body = 2;</code>
       */
      public Body.Builder addBodyBuilder() {
        return getBodyFieldBuilder().addBuilder(
            Body.getDefaultInstance());
      }
      /**
       * <code>repeated .netty.Message.Body body = 2;</code>
       */
      public Body.Builder addBodyBuilder(
          int index) {
        return getBodyFieldBuilder().addBuilder(
            index, Body.getDefaultInstance());
      }
      /**
       * <code>repeated .netty.Message.Body body = 2;</code>
       */
      public java.util.List<Body.Builder>
           getBodyBuilderList() {
        return getBodyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Body, Body.Builder, BodyOrBuilder>
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Body, Body.Builder, BodyOrBuilder>(
                  body_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }

      // optional bytes attachment = 8;
      private com.google.protobuf.ByteString attachment_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes attachment = 8;</code>
       */
      public boolean hasAttachment() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes attachment = 8;</code>
       */
      public com.google.protobuf.ByteString getAttachment() {
        return attachment_;
      }
      /**
       * <code>optional bytes attachment = 8;</code>
       */
      public Builder setAttachment(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        attachment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes attachment = 8;</code>
       */
      public Builder clearAttachment() {
        bitField0_ = (bitField0_ & ~0x00000004);
        attachment_ = getDefaultInstance().getAttachment();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:netty.Message)
    }

    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:netty.Message)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_netty_Message_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_Message_Header_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_netty_Message_Header_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_Message_Body_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_netty_Message_Body_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016Protocol.proto\022\005netty\"\226\002\n\007Message\022%\n\006h" +
      "eader\030\001 \002(\0132\025.netty.Message.Header\022!\n\004bo" +
      "dy\030\002 \003(\0132\023.netty.Message.Body\022\022\n\nattachm" +
      "ent\030\010 \001(\014\032\210\001\n\006Header\022\014\n\004type\030\001 \002(\007\022\014\n\004fr" +
      "om\030\002 \002(\t\022\n\n\002to\030\003 \002(\t\022\023\n\013delivery_id\030\004 \002(" +
      "\t\022\025\n\rdelivery_time\030\005 \002(\006\022\021\n\tdevice_id\030\006 " +
      "\002(\t\022\027\n\017device_platform\030\007 \002(\t\032\"\n\004Body\022\013\n\003" +
      "key\030\001 \002(\t\022\r\n\005value\030\002 \002(\tB\'\n\031cheetah.pred" +
      "ator.protocolB\nMessageBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_netty_Message_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_netty_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_netty_Message_descriptor,
              new String[] { "Header", "Body", "Attachment", });
          internal_static_netty_Message_Header_descriptor =
            internal_static_netty_Message_descriptor.getNestedTypes().get(0);
          internal_static_netty_Message_Header_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_netty_Message_Header_descriptor,
              new String[] { "Type", "From", "To", "DeliveryId", "DeliveryTime", "DeviceId", "DevicePlatform", });
          internal_static_netty_Message_Body_descriptor =
            internal_static_netty_Message_descriptor.getNestedTypes().get(1);
          internal_static_netty_Message_Body_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_netty_Message_Body_descriptor,
              new String[] { "Key", "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
